### PR TITLE
Add Mixer as a new provider

### PR DESCRIPTION
**Pull request by SirNickParks**
Tested this last night and it worked fine, apologizes if there's anything different in the test file. Haven't created many of those myself.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
There is also https://github.com/hapijs/bell/pull/314 any difference in the PR's?

**Comment by SirNickParks** [comment]
I haven't tested the other PR myself, but from looking at the code differences it looks like mine just passes the Travis CI check, doesn't include anything about yarn, has the mixer require placed alphabetically along with the rest in the providers index, and is a little cleaner looking (personal preference I suppose).

Other than that both should be functional.

**Comment by SirNickParks** [comment]
Any news on this? Would love to see it officially included in bell :)

**Comment by AdriVanHoudt** [comment]
cc @ldesplat

**Comment by ldesplat** [comment]
Thank you! And thanks for being super patient.

**Pull request merged**
