### PR TITLE
Pass `forceHttps` and `location` to v1 client

### PR DESCRIPTION
**Pull request by salzhrani**
Pass `forceHttps` and `location` to v1 client

### CODE REVIEW

**Comment by salzhrani** [comment]
coverage failing on line 510 ... not sure how to fix

**Comment by geek** [comment]
You should be fine to delete line 510 since you are always passing in the protocol from `info.protocol`

If you look at the html report for coverage it should show what is needed.

**Comment by salzhrani** [comment]
Thanks for the feedback,It is green now. Hope to see this land soon.

**Comment by geek** [comment]
@salzhrani this is now published with v2.7.1.  Thanks

**Pull request merged**
