### PR TITLE
Facebook

### PR DESCRIPTION
**Pull request by doron2402**
- Using  Facebook newest api version (2.8)
- Adding user picture to request

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
is there anything breaking about the upgrade to 2.8? would existing implementations just keep working?

**Comment by doron2402** [comment]
@AdriVanHoudt ,
not that I know of but I've updated that locally and it seems to be working fine.

**Comment by kamronbatman** [comment]
First, we should look into v2.9, which doesn't look like it has anything breaking between v2.7 and v2.8.  Also this PR requires updates to oauth.js and tests.

**Comment by ldesplat** [comment]
#311 got merged which takes care of this. I know I took a very long time, but thank you so much for persevering :)

**Pull request closed without merging**
