### PR TITLE
Fix clientSecret usage

### PR DESCRIPTION
**Pull request by qualquervalor**
The code was attempting to access the clientSecret with the wrong variable name.

### CODE REVIEW

**Comment by ulrikaugustsson** [comment]
The second commit should probably not be in the same PR.

**Comment by cjihrig** [comment]
@geek LGTM

**Comment by hofan41** [comment]
This was a rather large bug that somehow slipped through the unit tests. Wonder why the unit tests didn't catch this.

**Comment by cjihrig** [comment]
Likely because tests use mock data. PRs adding more/better tests are always welcome.

**Comment by fson** [comment]
Could this be merged and a new release pushed to npm? It seems that most providers are broken at the moment.

**Pull request merged**
