### PR TITLE
add weixin provider

### PR DESCRIPTION
**Pull request by hilanmiao**
Hello, I submitted a provider, but I don't know how to write test cases. can you help me？ @hueniverse
image
Does anyone know how to test this code?

### CODE REVIEW

**Comment by hilanmiao** [comment]
Hello, I submitted a provider, but I don't know how to write test cases. can you help me？ @hueniverse
image
Does anyone know how to test this code?

**Comment by hueniverse** [comment]
Great!

Just do what everyone else does, copy the tests of an existing provider that's close to yours in terms of options. Of course make sure to pick one using the right OAuth version. Let me know if you need more help.

**Comment by hilanmiao** [comment]
> Great!
> 
> Just do what everyone else does, copy the tests of an existing provider that's close to yours in terms of options. Of course make sure to pick one using the right OAuth version. Let me know if you need more help.

I have submitted a test case, but I think my test code is not rigorous enough. If necessary, please modify it.

**Comment by hueniverse** [comment]
Sorry, I didn't notice that your PR included changes to the internal implementation. That's not going to happen. Looks like Weixin is not at all compatible with the standard. It is not widely used enough to justify special casing it.

**Pull request closed without merging**
