### PR TITLE
added photo field in facebook.js to receive profile pic as well

### PR DESCRIPTION
**Pull request by satnam-sandhu**
receiving the facebook profile picture, which seemed to be broken.

### CODE REVIEW

**Comment by jordymeow** [comment]
I hope this will be merged :)

**Comment by hueniverse** [comment]
@satnam-sandhu update the PR to master and switch to normal size and I'll merge it.

**Comment by satnam-sandhu** [comment]
Okay I have changed the profile picture field to default and i very new to all this so i don't have much idea about passing those tests. Thank you!

**Comment by AdriVanHoudt** [comment]
@satnam-sandhu if you need help with the rebase/merge let us know!

**Comment by satnam-sandhu** [comment]
As my changes are approved. When will my pull request be merged with master? @AdriVanHoudt

**Comment by AdriVanHoudt** [comment]
When you have resolved the merge conflicts, you should see a `resolve conflicts` button at the bottom of this PR

**Pull request closed without merging**
