### PR TITLE
Added custom OAuth2 client authentication

### PR DESCRIPTION
**Pull request by cvillerm**
In relation with issue #285 to allow [custom OAuth2 client authentication](https://tools.ietf.org/html/rfc6749#section-2.3), this PR allows option `clientSecret` to be passed as an object, that will be used to be merged with Wreck request options when calling the token endpoint.

This can allow passing a client certificate (e.g. `clientSecret: { agent: new Https.Agent({ cert: myClientCert, key: myClientKey }) } `) to be used for client-certificate-based authentication when calling the OAuth2 Authorization Server token endpoint.

If clientSecret is formatted as a string, this is behaving as before (backward compatibility).

Unit tests and updated API.md included.
Test results:
```
122 tests complete
Test duration: 2905 ms
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
```

### CODE REVIEW

**Comment by feenst** [comment]
Any word on this?

**Comment by cvillerm** [comment]
@ldesplat, thanks for this review.
I updated the validation schema accordingly (and refreshed  from the latest master branch).

I ran local tests of the updated validation schema:

```js
const Joi = require('joi');

clientSecretSchema = {
    protocol: Joi.string(),
    secret: Joi.alternatives().when('protocol', {
        is: 'oauth',
        then: Joi.string().required().allow(''),
        otherwise: Joi.alternatives().try(Joi.string().allow(''), Joi.object())
    }).required()
};

Joi.assert({ protocol: 'oauth2', secret: { a: 12 } }, clientSecretSchema); // Pass

Joi.assert({ protocol: 'oauth', secret: 'a' }, clientSecretSchema); // Pass
Joi.assert({ protocol: 'oauth', secret: '' } , clientSecretSchema); // Pass

Joi.assert({ protocol: 'oauth2', secret: 'a' }, clientSecretSchema); // Pass
Joi.assert({ protocol: 'oauth2', secret: '' }, clientSecretSchema); // Pass

Joi.assert({ protocol: 'oauth2' }, clientSecretSchema); // Fail

Joi.assert({ protocol: 'oauth', secret: 12 }, clientSecretSchema); // Fail
Joi.assert({ protocol: 'oauth2', secret: 12 }, clientSecretSchema); // Fail
Joi.assert({ protocol: 'oauth', secret: { a: '12' } }, clientSecretSchema); // Fail
```

I didn't add formal unit tests as I am not sure that current tests are going down to this level of details, but if you think that I should do, let me know.

**Comment by feenst** [comment]
Is this good to merge?

**Comment by ldesplat** [comment]
Thanks!

**Pull request merged**
