### PR TITLE
[Update] Updates Facebook provider to v2.7

### PR DESCRIPTION
**Pull request by kamronbatman**
Updates Facebook provider to v2.7.
Tested with public profile options and is working.

### CODE REVIEW

**Comment by ldesplat** [comment]
For reference this is the changelog between the APIs.. In this case going from 2.3 (supported until July 2017) to 2.7.

https://developers.facebook.com/docs/apps/changelog

Take a look at the changes in permissions, would explain the changes. In our case, it doesn't impact us but it does impact if people are passing in extra permissions which leads me to think that this is a breaking change for our users.

I'll merge this in a major release but I am going on vacation for 8 days so it will have to wait that much extra time for now!

**Comment by kamronbatman** [comment]
Going from v2.3 to v2.7 is a big change.  There are a few deprecations and permission changes but that is minor compared to the improved performance and new endpoints/APIs.

Should we allow the user to specify the version through a field?  The Facebook provider is fairly simple and I think it can already support 2.x.

**Comment by kamronbatman** [comment]
@hueniverse I noticed you removed this from the 9.0 milestone.  Any particular reason? Will it be added to a milestone after that?

Thanks!

**Comment by ldesplat** [comment]
It will get done :) He removed it because he was doing a release of something else.

**Comment by kamronbatman** [comment]
I realized that and that is why I removed my comment.  I updated it to the latest master.  I figure we can rebase or squash when ready.  Also since facebook v2.8 is out, this _might_ be outdated and need to be replaced with a new PR that has new testing.

**Comment by kamronbatman** [comment]
Now that Facebook has moved beyond v2.7, should we consider a newer API version for the next milestone?

**Comment by kamronbatman** [comment]
Closing this out in favor of #311.

**Pull request closed without merging**
