### PR TITLE
Add trakt.tv provider

### PR DESCRIPTION
**Pull request by marcuspoehls**
The provider to support the [trakt.tv OAuth API is yet missing](http://docs.trakt.apiary.io/#introduction). This PR helps to add support for trakt.

It uses the extended trakt.tv user profile by default.

Hopefully this helps users to connect with trakt.tv’s OAuth API :)

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@ldesplat Ups, sorry. Will check and correct the tests. Thank you

**Comment by AdriVanHoudt** [comment]
```
Coverage: 99.94% (1/1601)
lib/providers/trakt.js missing coverage on line(s): 5
```
missing that 0.06% coverage 😲 😉

**Comment by marcuspoehls** [comment]
@AdriVanHoudt @ldesplat yeah, I saw the failing tests due to coverage. Can you please tell me how to add test coverage for `line 5` in `lib/providers/trakt.js`?

It's this line:

```
options = options || {};
```

in the [trakt.js](https://github.com/fs-opensource/bell/blob/bab0118e1596194f846afa5c7dda22d2acec94c8/lib/providers/trakt.js) provider.

**Comment by AdriVanHoudt** [comment]
So you need a test that covers passing options and one that covers it defaulting to {}

**Comment by marcuspoehls** [comment]
Thank you buddy. I didn’t notice at first what was missing. I thought the default option is fine, but —of course— needs testing as well 😄

**Comment by marcuspoehls** [comment]
@ldesplat Hi Loïs, I fixed the failing tests and coverage is at 100%. Any chance to get this merged? Thank you!

**Comment by ldesplat** [comment]
Failing tests are normal and nothing to worry about. Just new node globals and we're still on such old versions of our dependencies. Thank you!

**Comment by marcuspoehls** [comment]
@ldesplat @AdriVanHoudt Thank you for merging!

**Pull request merged**
