### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by aphuang2013**
adding pingfed support

### CODE REVIEW

**Comment by ldesplat** [comment]
Ahh, another federation server :+1:

Unfortunately, I merged another PR, so you'll have to rebase this. Also, could you provide some tests so that we can keep 100% test coverage?

If you have any questions, please ask them and I'll be glad to help you.

**Comment by aphuang2013** [comment]
it is no problem, I can rebase mime.   I'm not sure about the testing I
need to perform to get 100% test, is there a quick cheat sheet?

thx

On Sun, May 15, 2016 at 4:54 PM, Loïs Desplat <notifications@github.com>
wrote:

> Ahh, another federation server [image: :+1:]
>
> Unfortunately, I merged another PR, so you'll have to rebase this. Also,
> could you provide some tests so that we can keep 100% test coverage?
>
> If you have any questions, please ask them and I'll be glad to help you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hapijs/bell/pull/214#issuecomment-219322629>
>



-- 
peter huang

**Comment by ldesplat** [comment]
Unfortunately, the tests are not very good (For providers) but they're the best we have unless we set up accounts for each.

You can see in https://github.com/hapijs/bell/tree/master/test/providers . Just copy paste an existing one and plug in your provider where it makes sense. Verify it's the output you're truly expecting and it should bring to 100% test coverage.

**Comment by aphuang2013** [comment]
Will do, thx for the tips

On Wednesday, May 18, 2016, Loïs Desplat <notifications@github.com> wrote:

> Unfortunately, the tests are not very good (For providers) but they're the
> best we have unless we set up accounts for each.
>
> You can see in https://github.com/hapijs/bell/tree/master/test/providers
> . Just copy paste an existing one and plug in your provider where it makes
> sense. Verify it's the output you're truly expecting and it should bring to
> 100% test coverage.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/hapijs/bell/pull/214#issuecomment-220014957>
>


-- 
peter huang

**Comment by cvillerm** [comment]
It could be good as well to make this provider definition more generic by allowing other options to be passed such as configurable scopes... as this is configurable in each PingF implementation (see https://documentation.pingidentity.com/pingfederate/pf81/index.shtml#concept_authorizationEndpoint.html#concept_authorizationEndpoint).

Could also the OpenID id_token returned be made accessible (in the credentials object) so that it can be used if needed?

The line logging credentials to the console should also likely be removed.

Thanks

**Comment by aphuang2013** [comment]
I'm having some problem fixing the errors reported  in npm test.   It
stated the overage on line 5 and 7 is not done.   However, those the module
stuff,  what do I need to do to fix those?

=========
.............
  √ 106) authenticates with mock (31 ms)


106 tests complete
Test duration: 3093 ms
No global variable leaks detected
Coverage: 99.84% (2/1242)
lib/providers/pingfed.js missing coverage on line(s): 5, 7
Code coverage below threshold: 99.84 < 100
Linting results: No issues

npm ERR! Test failed.  See above for more details.
==================
...
line 5: const Bell = require('../../');
line 6: const Code = require('code');
line 7: const Hapi = require('hapi');
line 8: const Hoek = require('hoek');


On Wed, May 18, 2016 at 8:10 AM, Peter Huang <aphuang@gmail.com> wrote:

> Will do, thx for the tips
>
>
> On Wednesday, May 18, 2016, Loïs Desplat <notifications@github.com> wrote:
>
>> Unfortunately, the tests are not very good (For providers) but they're
>> the best we have unless we set up accounts for each.
>>
>> You can see in https://github.com/hapijs/bell/tree/master/test/providers
>> . Just copy paste an existing one and plug in your provider where it makes
>> sense. Verify it's the output you're truly expecting and it should bring to
>> 100% test coverage.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hapijs/bell/pull/214#issuecomment-220014957>
>>
>
>
> --
> peter huang
>
>


-- 
peter huang

**Comment by gergoerdosi** [comment]
You need to add tests similarly to the other providers: https://github.com/hapijs/bell/tree/master/test/providers

**Comment by aphuang2013** [comment]
I did add the pingfed.js provider in the test folders, that is how I get
through the steve.smith@example.com check.   However, I'm missing other
stuff.

On Mon, Jun 13, 2016 at 3:41 PM, Gergo Erdosi <notifications@github.com>
wrote:

> You need to add tests similarly to the other providers:
> https://github.com/hapijs/bell/tree/master/test/providers
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hapijs/bell/pull/214#issuecomment-225730235>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFB-WPDdZgBgfbJhjf6-oiLn6sv_yIOCks5qLdyPgaJpZM4IbH0v>
> .
>



-- 
peter huang

**Comment by PaulMougel** [comment]
If line 5 is this one:
```javascript
options = options || {};
```
then you'll have to test the creation of this provider with and without an `options` object.

You can look at the tests of the `github` provider: [here](https://github.com/hapijs/bell/blob/master/test/providers/github.js#L34) and [there](https://github.com/hapijs/bell/blob/master/test/providers/github.js#L107).

**Comment by aphuang2013** [comment]
thank, that was the key, I missed that. thanks for the explanation, I got
it fixed now

On Tue, Jun 14, 2016 at 6:35 AM, Paul Mougel <notifications@github.com>
wrote:

> If line 5 is this one:
>
> options = options || {};
>
> then you'll have to test the creation of this provider with and without an
> options object.
>
> You can look at the tests of the github provider: here
> <https://github.com/hapijs/bell/blob/master/test/providers/github.js#L34>
> and there
> <https://github.com/hapijs/bell/blob/master/test/providers/github.js#L107>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hapijs/bell/pull/214#issuecomment-225882298>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFB-WMSG7qHwq92VvY9RYhBSiLXDN38yks5qLq4YgaJpZM4IbH0v>
> .
>



-- 
peter huang

**Comment by ldesplat** [comment]
Make sure to push your new changes :)

**Comment by aphuang2013** [comment]
I try to rebase the stuff against master but it failed other tests (not my
pieces).   there are many new versions in package.json so I need node v5
now?

On Wed, Jun 15, 2016 at 9:19 AM, Loïs Desplat <notifications@github.com>
wrote:

> Make sure to push your new changes :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hapijs/bell/pull/214#issuecomment-226240091>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFB-WGvMZsjLiTSXxDGu0baMnaOJpFOdks5qMCYVgaJpZM4IbH0v>
> .
>



-- 
peter huang

**Comment by aphuang2013** [comment]
since rebase dif not work, I deleted my fork and restart.  everything is
came clean now

On Wed, Jun 15, 2016 at 11:27 AM, Peter Huang <aphuang@gmail.com> wrote:

> I try to rebase the stuff against master but it failed other tests (not my
> pieces).   there are many new versions in package.json so I need node v5
> now?
>
> On Wed, Jun 15, 2016 at 9:19 AM, Loïs Desplat <notifications@github.com>
> wrote:
>
>> Make sure to push your new changes :)
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/hapijs/bell/pull/214#issuecomment-226240091>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AFB-WGvMZsjLiTSXxDGu0baMnaOJpFOdks5qMCYVgaJpZM4IbH0v>
>> .
>>
>
>
>
> --
> peter huang
>



-- 
peter huang

**Comment by ldesplat** [comment]
Taken care of by #236

**Pull request closed without merging**
