### PR TITLE
Optional escapeScope configuration on schema

### PR DESCRIPTION
**Pull request by phoenixbox**
#### What's this PR do?
* The default encoding of scopes breaks for full url scopes such as the ones google uses like so:
```
https://www.googleapis.com/auth/admin.directory.user.readonly
```
* When these scopes are encoded, google doesnt recognize them and then throws an unknown scope error
* To get around this I added a configurable attribute on bell schema called `escapeScope` which defaults to `true`
* I set this value to `false` when I don't want the scopes escaped

#### Where should the reviewer start?
* `lib/index.js:72`
* ` lib/oauth.js:623`

##### Error state
image

* Encoded scopes in url
```
https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.domain.readonly%2Bhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.domain%2Bhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user.readonly%2Bhttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user
```

##### Solution State
image

* Un-encoded scopes in url
```
scope=profile+email+https://www.googleapis.com/auth/admin.directory.domain.readonly+https://www.googleapis.com/auth/admin.directory.domain+https://www.googleapis.com/auth/admin.directory.user.readonly+https://www.googleapis.com/auth/admin.directory.user
```

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
I have a google scope set up like `scope: ['profile', 'email', 'https://www.googleapis.com/auth/userinfo.email']` and that works fine so not sure what is resulting in the error for you since escaping is not the issue (with me at least)?

**Comment by phoenixbox** [comment]
Hmmm not sure what the difference is, maybe its specifically with the Admin SDK?

Heres an example of my full strategy:

```
server.auth.strategy('google-admin', 'bell', {
  provider: {
    protocol: 'oauth2',
    useParamsAuth: true,
    auth: 'https://accounts.google.com/o/oauth2/v2/auth',
    token: 'https://www.googleapis.com/oauth2/v4/token',
    scopeSeparator: '+',
    profile: function (credentials, params, get, callback) {
      get('https://www.googleapis.com/oauth2/v3/userinfo', null, (profile) => {
        credentials.provider = 'google';
        credentials.profile = {
          id: profile.sub,
          email: profile.email,
          display_name: profile.name,
          photo_url: profile.picture,
          scope: [
            'profile',
            'email',
            'https://www.googleapis.com/auth/admin.directory.domain.readonly',
            'https://www.googleapis.com/auth/admin.directory.user.readonly'
          ],
          raw: profile
        };

        return callback();
      });
    }
  },
  password: config.GOOGLE_COOKIE_PASSWORD,
  clientId: config.GOOGLE_CLIENT_ID,
  clientSecret: config.GOOGLE_CLIENT_SECRET,
  isSecure: false,
  escapeScope: false,
  scope: [
    'profile',
    'email',
    'https://www.googleapis.com/auth/admin.directory.domain.readonly',
    'https://www.googleapis.com/auth/admin.directory.user.readonly'
  ],
  providerParams: {
    access_type: 'offline'
  },
  cookie: 'googleAdmin'
});
```

Would you mind trying the Admin SDK scopes?

**Comment by AdriVanHoudt** [comment]
I don't have ` scopeSeparator: '+',` which would be my first guess of where things might go wrong

**Comment by phoenixbox** [comment]
@AdriVanHoudt damn I think that was it, somehow I didn't try that 🙈 feel le dumb

**Comment by AdriVanHoudt** [comment]
@phoenixbox I'm glad you got it working!

**Pull request closed without merging**
