### PR TITLE
Show error message from the auth service

### PR DESCRIPTION
**Pull request by Asuza**
Shows error message from _www-authenticate_ header, if available.

### CODE REVIEW

**Comment by Asuza** [comment]
That's strange, since that's exactly how I got the error message from Facebook to figure out what my configuration issue was. Is the content of `err.data` mocked somewhere? I suppose if each service handles error messages differently, this type of message might only apply to Facebook. I haven't tried failing to connect to anything else.

**Comment by AdriVanHoudt** [comment]
Hey @Asuza do you still want this?
If you are stuck on something or anything just let me know!

**Comment by Asuza** [comment]
I haven't had the time to look at it more. I'm hoping I'll have more free time soon, but I'll just have to see what happens.

**Comment by hueniverse** [comment]
No progress.

**Pull request closed without merging**
