### PR TITLE
fixed linting issues // now extends lab linting

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
I added special rule def in test files because it was used so much that fixing it would take a lot of time and the rule is more a precaution anyway, so be carefull with you res's in your tests kids :exclamation:

### CODE REVIEW

**Comment by ldesplat** [comment]
Thanks, I'll merge this once I figure out what is wrong with our tests. The last merged PR passed no problem :(

**Comment by AdriVanHoudt** [comment]
maybe a dep patch update or something?

**Comment by AdriVanHoudt** [comment]
Will rebase soon

**Comment by ldesplat** [comment]
No need it does it automatically when it can.

**Comment by AdriVanHoudt** [comment]
:+1:

**Pull request merged**
