### PR TITLE
update deprecated google api urls

### PR DESCRIPTION
**Pull request by egaba88**
this fixes the remaining piece of https://github.com/hapijs/bell/issues/66

### CODE REVIEW

**Comment by qualquervalor** [comment]
Documentation for these OpenIDConnect updates can be found here:
https://developers.google.com/identity/protocols/OpenIDConnect#discovery

The Discovery document for Google's OpenID Connect service may be retrieved from:
https://accounts.google.com/.well-known/openid-configuration

The referenced https://www.googleapis.com/oauth2/v3/userinfo is NOT available through Google's API Discovery Service https://developers.google.com/discovery/
https://www.googleapis.com/discovery/v1/apis
which is why I did not use it [#104](https://github.com/hapijs/bell/pull/104)

**Comment by geek** [comment]
@qualquervalor what are your thoughts on this PR, does it look like a good solution?

**Comment by qualquervalor** [comment]
[#108](https://github.com/hapijs/bell/pull/108) will supersede this and make these changes irrelevant

**Comment by geek** [comment]
Closing in favor of #108, thanks @egaba88

**Pull request closed without merging**
