### PR TITLE
New dropbox-v2 provider which uses Dropbox V2 API

### PR DESCRIPTION
**Pull request by klaronix**
The existing Dropbox provider uses Dropbox API V1 which has been deprecated in April 2016. New API V2 uses "RPC" style calls (i.e. POST) for requesting user account information. So far all providers are requesting account information by GET calls. There is a new provider config option now ("providerMethod") which can be set to 'post' in order to get account information by POST request (defaults to 'get').

[https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account](https://www.dropbox.com/developers/documentation/http/documentation#users-get_current_account)

### CODE REVIEW

**Comment by ldesplat** [comment]
This looks good on the first go. Maybe since you clearly pointed out that our existing dropbox implementation is no longer the preferred way, we can change this rather than adding a new dropbox-v2.

I depend on your to let us know if it breaks existing clients to do so, so that I know if this will be a major release or not.

What would make it a breaking release is if the profile response looks any different than before for example or if it supports different parameters than before. I would edge towards saying that yes it breaks existing clients and there is no issue for us to make a major release.

**Comment by klaronix** [comment]
Unfortunately Dropbox V2 api breaks clients because of different profile response. So I would go for a '-v2' provider rather than urging bell users to migrate on next update. The old api will be switched off on 06/28/2017; maybe until then we should keep the two providers.

**Comment by ldesplat** [comment]
I'll merge this in 8 days but if you could make the following modifications (i'll do them otherwise).

Use `Wreck.request` and pass the method instead of your current way. As well as default to `'get'` internally (along with the current default in the Joi schema).

Also, some documentation on the v2 provider would be appreciated.

**Comment by ldesplat** [comment]
I have not forgotten about this PR. I've got some work in progress that will incorporate it :)

**Comment by klaronix** [comment]
@ldesplat: Do you think, we get this PR integrated? Because I have another one ;=) It's commit 		36bd1f1 from today, which adds support to pass a custom Wreck agent (this allows to authenticate behind a proxy).

**Comment by ldesplat** [comment]
Can you remove the custom agent from that branch and make another PR. I'll merge this when that's done.

**Comment by klaronix** [comment]
OK. PR is now "agent free".

**Pull request merged**
