### PR TITLE
Fixes #266 Implements azure active directory as bell azuread module

### LINKED ISSUE #266: Implement Azure Active Directory authentication for enterprise AD logins
## Feature request
The authentication for [azure active directory](https://azure.microsoft.com/en-in/documentation/articles/active-directory-whatis/) should be fairly similar to the one in office 365 except that the modifications should be as follows.
```js
// azuread.js
'use strict';

exports = module.exports = function (options) {
    options = options || {};
    const tenantId = options.tenant || 'common';

    return {
        protocol: 'oauth2',
        useParamsAuth: true,
        auth: 'https://login.microsoftonline.com/'+ tenantId +'/oauth2/authorize',
        token: 'https://login.microsoftonline.com/'+ tenantId +'/oauth2/token',
        scope: ['openid','offline_access', 'profile'],
        profile: function (credentials, params, get, reply) {

            get('https://login.microsoftonline.com/'+ tenantId +'/openid/userinfo', null, (profile) => {

                credentials.profile = {
                    id: profile.oid,
                    displayName: profile.name,
                    email: profile.upn,
                    raw: profile
                };
                return reply();
            });
        }
    };
};
```
and the example should look something like this
```js
server.auth.strategy('azuread', 'bell', {
      provider: 'azuread',
      password: 'cookie_encryption_password_secure',
      clientId: 'bdXXXXXX-5XXX-4XXX-aXXX-6XXXXXXXX9',
      clientSecret: 'mjXXXXXXXXXXXXXEe+l3XXXXXXXXXXXXkh8=',
      tenantId: 'XXXXXX-YYYYYY-XXXXXXXXXX-YYYYYYYYYY-ZZZZZZZ',
      providerParams: {
        response_type: 'code'
      },
      scope: ['openid', 'offline_access', 'profile'],
      isSecure: false
    });
```
When I try to fix this and use it I receive an error as follows
```
FATAL CLI ERROR TypeError: Cannot read property 'call' of undefined
```
I would love to make the patch for this if someone could help me through in patching this.

I've currently put the code I put up above into `office365.js` and have been successfully able to obtain a successful authentication response as follows for the `credentials.profile` object

```js
{ 
  id: '5XXXXXX-8XXX-4XXX-bXXX-aXXXXXXXX',
  displayName: 'Sudheesh Singanamalla',
  email: 'susingan@microsoft.com',
  raw:
   { amr: '["rsa","mfa"]',
     family_name: 'Singanamalla',
     given_name: 'Sudheesh',
     in_corp: 'true',
     ipaddr: 'AAA.AAA.AAA.AAA',
     name: 'Sudheesh Singanamalla',
     oid: '5XXXXXX-8XXX-4XXX-bXXX-aXXXXXXXX',
     onprem_sid: 'SXXXXXXXX77XXXXXXXXXXXXXXXXXXX7-2XXXX3',
     sub: 'gJXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXB4',
     tid: '7XXXXXXX-8XXX-4XXX-9XXX-2XXXXXXXXXX',
     unique_name: 'susingan@microsoft.com',
     upn: 'susingan@microsoft.com',
     ver: '1.0' 
   } 
}
```

### PR DESCRIPTION
**Pull request by sudheesh001**
Signed off by: Sudheesh Singanamalla <susingan@microsoft.com>

### CODE REVIEW

**Comment by kamronbatman** [comment]
@sudheesh001 Thank you so much for the contribution!

I know it is minor, but can you please fix the linting?
```
Linting results:
	/home/travis/build/hapijs/bell/lib/providers/azuread.js:
		Line 3: hapi/hapi-scope-start - Missing blank line at beginning of function.
		Line 10: space-infix-ops - Infix operators must be spaced.
		Line 10: space-infix-ops - Infix operators must be spaced.
		Line 11: space-infix-ops - Infix operators must be spaced.
		Line 11: space-infix-ops - Infix operators must be spaced.
		Line 15: space-infix-ops - Infix operators must be spaced.
		Line 15: space-infix-ops - Infix operators must be spaced.
```

Thanks!

**Comment by sudheesh001** [comment]
@kamronbatman Sure, I've fixed the linting issues now. :smile:

**Comment by ldesplat** [comment]
Thank you! Now, once you understand how the tests are done, I think you could make this PR 100% good to go :)

See https://github.com/hapijs/bell/blob/master/test/providers/google.js#L45 as a reference. You will see I've highlighted Line 45 which basically tells you that we mock all the responses. This is done because the tests run fast & more importantly we don't have a proper way to store & share secrets so that we can run our tests directly against the providers.

So the gist of it is copy another test for one of the providers. Change the profile mock to reflect what azuread would respond with and then https://github.com/hapijs/bell/blob/master/test/providers/google.js#L45 change what we should be expecting as results.
Make sure to also change this line to your provider: https://github.com/hapijs/bell/blob/master/test/providers/google.js#L34

That's it. That usually covers everything. I don't see any if checks in your code so 1 test will suffice.

**Comment by sudheesh001** [comment]
@ldesplat Thanks, having a look at the google test made it clear on how the tests are happening. I've implemented the tests for the azuread integration and this pull request is now hopefully complete. Please review. 😄

**Comment by sudheesh001** [comment]
@kamronbatman @ldesplat ; ping :smile: Did you have a chance to look through this ?

**Comment by ldesplat** [comment]
Thank you for your work on this. Making the 8.3.0 release right now.

I schedule 1 hour, two days a week, to work on Bell but depending on other priorities it may get bumped! 💯

**Comment by wy193777** [comment]
When users wants to use this, just put `azuread` on provide field like bellow? The list of provides on API.md doesn't include `azuread`, so I'm not sure how to use it.
```
server.auth.strategy('azure-ad', 'bell', {
        provider: 'azuread',
        password: 'cookie_encryption_password_secure',
        clientId: 'my_azure_client_id',
        clientSecret: 'my_azure_client_secret',
        isSecure: false     // Terrible idea but required if not using HTTPS especially if developing locally
    });
```

**Pull request merged**
