### PR TITLE
Add Stripe as a new provider

### PR DESCRIPTION
**Pull request by sholladay**
Time to make some $$$, yo.

This PR adds [Stripe](https://stripe.com), one of the most popular payment platforms, as a new provider. With this, we can use [Stripe Connect](https://stripe.com/connect) to help sellers sign up or log in to our platform and earn a living.

Stripe OAuth docs: https://stripe.com/docs/connect/oauth-reference

### CODE REVIEW

**Comment by sholladay** [comment]
Anyone have time for a review? @ldesplat @Marsup

Should be pretty uncontroversial. 🤞

**Comment by sholladay** [comment]
@nlf I think this module needs a new maintainer.

**Comment by nlf** [comment]
it appears you may be correct

**Comment by Marsup** [comment]
Already tried in https://github.com/hapijs/bell/issues/253, no one showed up, are you candidate ?

**Comment by ldesplat** [comment]
Thanks :) You asked for controversial and you got it! I am definitely not the best person to maintain bell anymore as can be seen in how slow I merge this. But all your efforts are very appreciated.

**Comment by sholladay** [comment]
Better late than never. Also, I just want to say thanks for the time and effort you have put in. Open source is important but often with little tangible reward. I appreciate it. ❤️ 

If I were more familiar with OAuth, I would potentially volunteer to be maintainer. Not sure I'm a good fit right now, but I will spread the word.

**Pull request merged**
