### PR TITLE
facebook picture field added to get profile picture

### PR DESCRIPTION
**Pull request by satnam-sandhu**
Updated test Case for facebook but when running tests it shows error in other files.
This is my error:
```
Coverage: 92.13% (124/1575)
lib/oauth.js missing coverage on line(s): 312, 313, 316, 346
lib/providers/arcgisonline.js missing coverage on line(s): 21, 24, 26, 28
lib/providers/auth0.js missing coverage on line(s): 29, 30
lib/providers/azuread.js missing coverage on line(s): 24, 26, 29
lib/providers/bitbucket.js missing coverage on line(s): 19, 21
lib/providers/digitalocean.js missing coverage on line(s): 23, 24, 26
lib/providers/discord.js missing coverage on line(s): 20, 22
lib/providers/dropbox-v2.js missing coverage on line(s): 21, 22
lib/providers/dropbox.js missing coverage on line(s): 20, 21
lib/providers/fitbit.js missing coverage on line(s): 21, 23
lib/providers/foursquare.js missing coverage on line(s): 20, 23, 25, 26, 28
lib/providers/github.js missing coverage on line(s): 30, 32
lib/providers/gitlab.js missing coverage on line(s): 24, 25
lib/providers/google.js missing coverage on line(s): 21, 23
lib/providers/googleplus.js missing coverage on line(s): 21, 23
lib/providers/instagram.js missing coverage on line(s): 24, 29, 31, 32, 35, 36
lib/providers/linkedin.js missing coverage on line(s): 30
lib/providers/live.js missing coverage on line(s): 21, 23, 31
lib/providers/medium.js missing coverage on line(s): 23, 25
lib/providers/meetup.js missing coverage on line(s): 24, 25
lib/providers/mixer.js missing coverage on line(s): 22, 24, 26, 27
lib/providers/office365.js missing coverage on line(s): 21, 23
lib/providers/okta.js missing coverage on line(s): 29, 31
lib/providers/phabricator.js missing coverage on line(s): 30, 32, 34, 36
lib/providers/pingfed.js missing coverage on line(s): 26, 28
lib/providers/pinterest.js missing coverage on line(s): 23, 25, 27, 29
lib/providers/reddit.js missing coverage on line(s): 25, 28, 30, 31
lib/providers/salesforce.js missing coverage on line(s): 40, 41, 42, 44, 45
lib/providers/slack.js missing coverage on line(s): 22, 25, 27, 28, 31, 35, 36, 37, 38
lib/providers/spotify.js missing coverage on line(s): 28, 29
lib/providers/stripe.js missing coverage on line(s): 24, 26, 27
lib/providers/trakt.js missing coverage on line(s): 31, 33, 35, 36
lib/providers/tumblr.js missing coverage on line(s): 21, 22
lib/providers/twitch.js missing coverage on line(s): 22, 24, 26, 27
lib/providers/twitter.js missing coverage on line(s): 35, 36, 43
lib/providers/vk.js missing coverage on line(s): 20, 23, 25, 26, 28
lib/providers/wordpress.js missing coverage on line(s): 25, 29, 31, 33, 34, 35, 36, 37
lib/providers/yahoo.js missing coverage on line(s): 13, 21, 23, 33
Code coverage below threshold: 92.13 < 100
```

### CODE REVIEW

**Comment by satnam-sandhu** [comment]
@AdriVanHoudt I closed my last PR and sent a fresh one but these tests!! Sorry for disturbing but i really want to learn more b testing and CI.

**Comment by AdriVanHoudt** [comment]
Hi @satnam-sandhu The first commit's build failed due to Travis I think, I can't get the logs so seems like an issue on their end.

Am I correct to assume that the final implementation asks for the picture but you will get it from the raw profile?

**Comment by satnam-sandhu** [comment]
@AdriVanHoudt Yes that seemed like the only way possible for me at the moment. But i think that there should be picture field in the main profile object. But not possible for me to implement it right now. Will learn how to deal with Travis tests and would try to update it soon.

**Comment by AdriVanHoudt** [comment]
It looks like all your tests run fine (there was a small Travis hiccup).
I will merge this already since it is good to go and then you can take a jab at adding it to the profile object. 
It should definitely be possible since (I think) Discord already does something similar.

**Pull request merged**
