### PR TITLE
WordPress Provider

### PR DESCRIPTION
**Pull request by pankajpatel**
WordPress provider on oauth2

### CODE REVIEW

**Comment by Marsup** [comment]
It will need to be rebased on a more recent commit.

**Comment by pankajpatel** [comment]
how do I do that?

**Comment by ldesplat** [comment]
I like to do it this way:
`git remote add upstream https://github.com/hapijs/bell`
The follow: https://help.github.com/articles/syncing-a-fork/
Then it will tell you there are conflits, so you will need to manually resolve them. Follow these directions: https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

If all that really confuses you, you can do it the old way. First backup your work. Then delete your github fork and recreate it again so you are at the latest. Then apply your work back on top of that and resubmit a new PR! But you should get used to the above instructions.

Good Luck!

**Comment by pankajpatel** [comment]
Thanks @ldesplat ! 
That's a really good help. Let me try the rebase now.

**Comment by pankajpatel** [comment]
I have merged the changes and has no conflict now. Does it look good?

**Comment by ldesplat** [comment]
Thank you, will make a new release right now 7.5.0!

**Pull request merged**
