### PR TITLE
FB custom scope + upgrade api version

### PR DESCRIPTION
**Pull request by doron2402**
- Upgrade FB version from `2.9` to `3.1`
- Add the ability to update Facebook login scope

### CODE REVIEW

**Comment by doron2402** [comment]
@AdriVanHoudt anything I should add?

**Comment by AdriVanHoudt** [comment]
@doron2402 looks good, is there a breaking api change between these versions?

**Comment by doron2402** [comment]
thanks @AdriVanHoudt did some testing and double checked Facebook api docs seems fine:
https://developers.facebook.com/docs/graph-api/reference/v3.1/user

**Comment by doron2402** [comment]
oops I mean to comment not to close it.

**Comment by doron2402** [comment]
@AdriVanHoudt can we merge this?

**Comment by AdriVanHoudt** [comment]
I can only see https://developers.facebook.com/docs/graph-api/changelog/version3.0#login which I don't think is breaking in our case.

**Pull request merged**
